import sys
from robotremoteserver import RobotRemoteServer


class ExampleRemoteLibrary(object):
    """Example library to be used with Robot Framework's remote server.

    This documentation is visible in docs generated by `Libdoc`.
    """

    def start_applicaiton_here(self, name):
        sys.__stdout__.write("Call from Remote Client for start_applicaiton_here\n")
        print "Call from Remote Client for start_applicaiton_here\n"
        return True

    def stop_application_here(self, name):
        sys.__stdout__.write("Call from Remote Client for stop_application_here\n")
        print "Call from Remote Client for stop_application_here\n"
        raise Exception("Just for a Test")
        return True


if __name__ == '__main__':
    RobotRemoteServer(ExampleRemoteLibrary(), *sys.argv[1:])
    sys.exit(0)
