import sys
from robotremoteserver import RobotRemoteServer


class ExampleRemoteLibrary(object):
    """Example library to be used with Robot Framework's remote server.

    This documentation is visible in docs generated by `Libdoc`.
    """

    def start_applicaiton_here(self, name):
        sys.__stdout__.write("Call from Remote Client for start_applicaiton_here\n")
        # os.system("c:\tm500.ext --opt ")
        return "Starting: %s" % name

    def stop_application_here(self, name):
        sys.__stdout__.write("Call from Remote Client for stop_application_here\n")
        return "Stop: %s" % name


if __name__ == '__main__':
    RobotRemoteServer(ExampleRemoteLibrary())
